# permissions for end users to view apexords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apexords-viewer-role
rules:
- apiGroups:
  - operator.apexords-operator
  resources:
  - apexords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.apexords-operator
  resources:
  - apexords/status
  verbs:
  - get
