
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - theapexords.apexords-operator
  resources:
  - apexords
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - theapexords.apexords-operator
  resources:
  - apexords/status
  verbs:
  - get
  - update
  - patch
