apiVersion: theapexords.apexords-operator/v1
kind: ApexOrds
metadata:
  name: apexords-sample
spec:
  # Add fields here
  dbname: psqlcdb
  dbservice: psqlpdb
  ordsname:  psqlords
  #apexruntimeonly: True 
